"""create users identity table

Revision ID: ea78aaa3052f
Revises: e24e9800e454
Create Date: 2026-08-04 16:45:01.762846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea78aaa3052f'
down_revision: Union[str, Sequence[str], None] = 'e24e9800e454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anonymous_hash', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_users_spam_hash'), table_name='users')
    op.create_index(op.f('ix_users_anonymous_hash'), 'users', ['anonymous_hash'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'karma')
    op.drop_column('users', 'spam_hash')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rank', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('spam_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('karma', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_anonymous_hash'), table_name='users')
    op.create_index(op.f('ix_users_spam_hash'), 'users', ['spam_hash'], unique=True)
    op.drop_column('users', 'anonymous_hash')
    # ### end Alembic commands ###
